export {default as Home} from "./Home"
export {default as Authentication } from "./Authentication"
export {default as SignUp} from "./SignUp"
export {default as Playlists} from "./Playlists"
export {default as Search} from "./Search"
export {default as Friends} from "./friends"
export {default as Charts} from "./charts"
export {default as Party} from "./party"